### ISSUE TITLE
Latex support

### ISSUE THREAD

**Issue by JaafarRammal** [ARESxCyber/ARESxCyber.github.io#6]
Add latex support for write-ups in sub-sections

**Comment by ghost** [comment]
Seems to only be a problem with embedded markdown files, so a temporary workaround is to paste all markdown with katex in the main markdown file of the docs subdirectories.

**Comment by JaafarRammal** [comment]
yeah true, although it would make the repo folders a bit "ugly" that's why I was looking for a workaround if possible :) but I guess that's the way

**Comment by JaafarRammal** [comment]
I saw you PR now, I think yes that should resolve it since it's just within the CTF write-ups file 👍 thanks for checking that!
